version: '3'

services:
    validator:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 80:3000
            - 9229:9229
        volumes:
            - ./src:/var/www/app/src
        command: 'nodemon --inspect src/index.js'