version: '3'

services:
    validator:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        command: 'node src/index.js'
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure