version: '3'

services:
    validator:
        command: 'nodemon --inspect dist/index.js'
        volumes:
            - ./src:/var/www/app/src
            - ./dist:/var/www/app/dist
        ports:
            - 80:3000
            - 9229:9229