version: '3'

services:
    validator:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 80:3000
            - 9229:9229
        volumes:
            - ./src:/var/www/app/src
        command: 'nodemon --inspect src/index.js'
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure