version: '3'

services:
    validator:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 80:3000
            - 9229:9229
        volumes:
            - ./server:/var/www/app/server
        command: 'nodemon --inspect server/index.js'